language: node_js

node_js:
  - "4"
  - "5"
  - "6"

sudo: false

branches:
  only:
    - master

cache: yarn

install:
  - npm install -g yarn
  - yarn install

script:
  - yarn --version
  - yarn run check
